#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090,SC1091
. "${SCRIPT_DIR}/../poshlib.sh" || exit 1
use swine

for i in "$SCRIPT_DIR"/test-*; do
	$i || echo "$i failed!"
done
