#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090,SC1091
. "${SCRIPT_DIR}/../poshlib.sh" || exit 1
use strict
use utils

for i in "$SCRIPT_DIR"/test-*; do
	[[ -x $i ]] || continue
	echo "Running $i"
	$i || echo "$i failed in bash version ${BASH_VERSION}!"
done
