#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh || exit 1

### detect_shell ###

if [ "$__posh__detected__shell" != "bash" ]; then
	echo "Shell not detected, expected 'bash' got '$output'"
	exit 1
fi

### prependpath ###

path=foo:bar
path=$(__posh__prependpath $path ../foo)
path=$(__posh__prependpath $path .)
if [ "$path" != "${__posh__stacktrace##*:}:${__posh__stacktrace##*:}/../foo:foo:bar" ]; then
	echo "Path prepending not working: path = $path"
fi

