#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh
use swine

# say
test="Hello \n this should not be line broken"
if [ "$test" != "$(say "$test")" ]; then
    die 1 "failure in say"
fi

# warn
if [ "$test" != "$(warn "$test" 2>&1)" ]; then
    die 1 "failure in warn"
fi

# contains
contains wibble foo bar wibble

# die
die 0 "" 2>/dev/null
