#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh || exit 1
use swine
use rposh

if [ "${1:-}" == "" ]; then
    rscript localhost --ssh-user=$USER --sudo-user=$USER "${BASH_SOURCE[0]}" "last" "test"
elif [ "${1:-}" != "last" ]; then
    die 1 "Mangled arguments to test-rposh"
fi
