#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh || exit 1
use swine

# say
test="Hello \n this should not be line broken"
if [ "$test" != "$(say "$test")" ]; then
    die 1 "failure in say"
fi

# warn
if [ "$test" != "$(warn "$test" 2>&1)" ]; then
    die 1 "failure in warn"
fi

# contains
contains wibble foo bar wibble

# error handling
tempfile=$(mktemp)
cat <<EOF >$tempfile
#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh || exit 1
use swine
ls FILEDOESNOTEXIST 2>/dev/null
EOF
if output=$(/bin/bash $tempfile 2>&1); then
    die 1 "failure in error handling: died with no error"
else
    if [ $? != 2 ]; then
	die 1 "failure in error handling: died with wrong error number"
    fi
fi
if [ "$output" != "errexit 2 on line 4 $tempfile" ]; then
    die 1 "failure in error handling: died with wrong error message ($output)"
fi
rm $tempfile

# die
die 0 "" 2>/dev/null
