#!/bin/bash
# shellcheck disable=SC1090,SC1091
. "$(dirname "${BASH_SOURCE[0]}")/../poshlib.sh" || exit 1
use strict
use utils
use rposh

if [ "${1:-}" == "" ]; then
    ssh localhost true || die 0 "rposh cannot be tested without ssh, skipping test..."
    result=$(
        e=
        try rscript ",localhost,," --ssh-user="$USER" --sudo-user="$USER" "${BASH_SOURCE[0]}" '\[last\]' 'SHOULD NOT BE DISPLAYED'
        if catch e; then
            say "ERROR $e"
        fi
    )
    if [ "$result" != '\[last\]' ]; then
        die 1 "Received unexpected output: '$result' != '\\[last\\]'"
    fi
elif [ "${1:-}" != '\[last\]' ]; then
    die 1 "Mangled arguments to test-rposh: '${1:-}' != '\\[last\\]'"
else
    say "$1"
fi
