#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh

### detect_shell ###

if [ "$__posh__detected__shell" != "bash" ]; then
	echo "Shell not detected, expected 'bash' got '$output'"
	exit 1
fi

