#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. ${SCRIPT_DIR}/../poshlib.sh || exit 1
use swine
use parse-opt

eval $(parse-opt-init)

#####
# Set defaults here e.g. via envars, config
#####

DEBUG=
VERBOSE=
FORCE=
OUTPUT=
INPUT=

PO_SHORT_MAP["d::"]="DEBUG=x y z"
PO_SHORT_MAP["v"]="VERBOSE"
PO_SHORT_MAP["f"]="FORCE"

PO_LONG_MAP["output:"]="OUTPUT"
PO_LONG_MAP["input:"]="INPUT"
PO_LONG_MAP["verbose"]="VERBOSE"
PO_LONG_MAP["force"]="FORCE"

declare -A expected_output
expected_output[' ']=",,,,;"
expected_output['foo bar wibble']=",,,,;foo bar wibble"
expected_output['foo -d bar wibble']="x y z,,,,;foo bar wibble"
expected_output['foo bar -d- wibble']="-,,,,;foo bar wibble"
expected_output['foo -- bar -d- wibble']=",,,,;foo bar -d- wibble"
expected_output['-f --no-force']=",false,,,;"
expected_output['--no-force -f']=",true,,,;"
expected_output['--output=- --input "--" ']=",,,-,--;"
expected_output['--output="A +" --input "a # c" ']=",,,A +,a # c;"
#expected_output['-f -x -d']=",true,,,;-f -x -d"

for input in "${!expected_output[@]}"; do
    eval set -- $input
    eval $(parse-opt)
    output="${DEBUG:-},${FORCE:-},${VERBOSE:-},${OUTPUT:-},${INPUT:-};$*"
    if [[ "$output" != "${expected_output[$input]}" ]]; then
        echo "Failed on '$input'"
        echo "   expect '${expected_output[$input]}'"
        echo "      got '$output'"
    fi
    DEBUG= FORCE= VERBOSE= OUTPUT= INPUT=
done

# Now do the same for parse-opt-simple

PO_SIMPLE_PREFIX="TEST_"
PO_SIMPLE_FLAGS="VERBOSE force"
PO_SIMPLE_PARAMS="OUTPUT input"

expected_output=()

expected_output[' ']=",,,,;"
expected_output['foo bar wibble']=",,,,;foo bar wibble"
expected_output['--force --no-force']=",false,,,;"
expected_output['--no-force --force']=",true,,,;"
expected_output['--output=- --input "--" ']=",,,-,--;"
expected_output['--output="A +" --input "a # c" ']=",,,A +,a # c;"

for input in "${!expected_output[@]}"; do
    eval set -- $input
    eval $(parse-opt-simple)
    output=",${TEST_FORCE:-},${TEST_VERBOSE:-},${TEST_OUTPUT:-},${TEST_INPUT:-};$*"
    if [[ "$output" != "${expected_output[$input]}" ]]; then
        echo "Failed on '$input'"
        echo "   expect '${expected_output[$input]}'"
        echo "      got '$output'"
    fi
    TEST_FORCE= TEST_VERBOSE= TEST_OUTPUT= TEST_INPUT=
done
