#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "$SCRIPT_DIR/../poshlib.sh" || exit 1
use swine
use flatten

if [ "$*" = "last" ]; then
    flatten "${BASH_SOURCE[0]}"
    exit 0
fi

tmpdir=$(mktemp -d)

flatten "${BASH_SOURCE[0]}" > "$tmpdir/file1"
chmod +x "$tmpdir/file1"

"$tmpdir/file1" last > "$tmpdir/file2"

if ! diff -q "$tmpdir/file1" "$tmpdir/file2" 2>/dev/null; then
    die 1 "flattening not idempotent"
fi

### test path dependence ###

cp -r "$SCRIPT_DIR/.." "$tmpdir/poshlib"
cat <<EOF > "$tmpdir/command"
#!/bin/bash
SCRIPT_DIR=\$(dirname "\${BASH_SOURCE[0]}")
. \$SCRIPT_DIR/poshlib/poshlib.sh || exit 1
use swine
# do nothing
:
EOF
/bin/bash "$tmpdir/command"
flatten "$tmpdir/command" > "$tmpdir/newcommand"
/bin/bash "$tmpdir/newcommand"
