#!/bin/bash
. $(dirname "${BASH_SOURCE[0]}")/../poshlib.sh
use swine
use flatten

if [ "$*" = "last" ]; then
    flatten "${BASH_SOURCE[0]}"
    exit 0
fi

tmpdir=$(mktemp -d)

flatten "${BASH_SOURCE[0]}" > $tmpdir/file1
chmod +x "$tmpdir/file1"

$tmpdir/file1 last > $tmpdir/file2

if ! diff -q "$tmpdir/file1" "$tmpdir/file2" 2>/dev/null; then
    die 1 "flattening not idempotent"
fi
