#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f $0))
. $SCRIPT_DIR/../poshlib.sh || exit 1
use swine
use ason
use ason/lowlevel

failure=0
fail() {
    echo "FAIL: $1"
    let ++failure
}

# Test tests

__ason__is_plaintext_entity "$_PAD" || fail __ason__is_plaintext_entity
__ason__is_type_entity "$_TABLE" || fail __ason__is_type_entity
__ason__is_entity "$_UNDEF" || fail __ason__is_entity

# Constructor tests

testquote="${__AS__SOH}${_PAD}${__AS__US}${_QUOTE}${__AS__STX}${_PAD}test${_PAD}${__AS__ETX}${__AS__EOD}"
[[ $(_QUOTE "test") == "$testquote" ]] || fail _QUOTE

testlist="${__AS__SOH}${_PAD}${__AS__US}${_LIST}${__AS__STX}${_PAD}test1${_PAD}${__AS__US}${_PAD}${testquote}${_PAD}${__AS__ETX}${__AS__EOD}"
[[ $(_LIST "test1" "$testquote") == "$testlist" ]] || fail _LIST

[[ $(_SPLIT , "foo,bar,wibble") == $(_LIST "foo" "bar" "wibble" ) ]] || fail _SPLIT

# Metadata tests

[[ $(_TYPE "${testquote}") == "$_QUOTE" ]] || fail "_TYPE 1"
[[ $(_TYPE "test") == "$_UNDEF" ]] || fail "_TYPE 2"

exit $failure
