#!/bin/bash
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "$SCRIPT_DIR/../poshlib.sh" || exit 1
use-from ".."

tmpfile=$(mktemp)

# Beware the substitutions in the following!
cat <<EOF >"$tmpfile"
#!/bin/bash
. "$SCRIPT_DIR/../poshlib.sh" || exit 1
__posh__usepath="\$__posh__usepath"
use main

test() {
	echo "\$@"
}

main test "No error"
EOF

output=$(bash "$tmpfile")
if [ "$output" != "No error" ]; then
	echo "Error in main(), code not reached: output='$output'"
	exit 1
fi

# Beware the substitutions in the following!
cat <<EOF >"$tmpfile"
#!/bin/bash
. "$SCRIPT_DIR/../poshlib.sh" || exit 1
__posh__usepath="\$__posh__usepath"
use main

main eval "echo Error in main(), this code should never be reached; exit 1"
EOF

# shellcheck disable=SC1090
. "$tmpfile"

rm "$tmpfile"
