#!/bin/bash

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
# shellcheck disable=SC1090
. "${SCRIPT_DIR}/../poshlib.sh" || exit 1
use swine
use keyval

tmpfile=$(mktemp)

cat <<EOF > "$tmpfile"
FOO=foo
FOO2=foo2
EOF

warn "$(keyval-read "$tmpfile")"
eval $(keyval-read "$tmpfile")
[[ "$FOO" == "foo" ]]

keyval-add "$tmpfile" BAR bar1
out="$(keyval-read "$tmpfile" BAR)"
warn "\"$out\" == \"BAR=bar1\""
[[ "$out" == "BAR=bar1" ]]

keyval-add --no-update "$tmpfile" BAR bar2
out="$(keyval-read "$tmpfile" BAR)"
warn "\"$out\" == \"BAR=bar1\""
[[ "$out" == "BAR=bar1" ]]

keyval-add "$tmpfile" BAR bar3
out="$(keyval-read "$tmpfile" BAR)"
warn "\"$out\" == \"BAR=bar3\""
[[ "$out" == "BAR=bar3" ]]

keyval-update "$tmpfile" BAR bar4
out="$(keyval-read "$tmpfile" BAR)"
warn "\"$out\" == \"BAR=bar4\""
[[ "$out" == "BAR=bar4" ]]

keyval-update --no-add "$tmpfile" WIBBLE wibble
out="$(keyval-read "$tmpfile" WIBBLE)"
warn "\"$out\" == \"\""
[[ "$out" == "" ]]

keyval-delete "$tmpfile" BAR
out="$(keyval-read "$tmpfile" BAR)"
warn "\"$out\" == \"\""
[[ "$out" == "" ]]

# Handling of special characters
val="bar1\$foo bar=!!"
keyval-add "$tmpfile" BAR "$val"
eval $(keyval-read "$tmpfile" BAR)
warn "\"$BAR\" == \"$val\""
[[ "$BAR" == "$val" ]]

# Array handling
keyval-add "$tmpfile" "ARRAY[key]" arrayval
out="$(keyval-read "$tmpfile" ARRAY)"
warn "\"$out\" == \"ARRAY[key]=arrayval\""
[[ "$out" == "ARRAY[key]=arrayval" ]]

keyval-update "$tmpfile" "ARRAY[key3]" arrayval3
keyval-delete "$tmpfile" "ARRAY[key3]"
out="$(keyval-read "$tmpfile" ARRAY)"
warn "\"$out\" == \"ARRAY[key]=arrayval\""
[[ "$out" == "ARRAY[key]=arrayval" ]]

keyval-update "$tmpfile" "ARRAY[key]" arrayval2
out="$(keyval-read "$tmpfile" ARRAY)"
warn "\"$out\" == \"ARRAY[key]=arrayval2\""
[[ "$out" == "ARRAY[key]=arrayval2" ]]

keyval-delete "$tmpfile" ARRAY
out="$(keyval-read "$tmpfile" ARRAY)"
warn "\"$out\" == \"\""
[[ "$out" == "" ]]
